on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo build -r --verbose
    - run: cargo test --verbose
    - run: cargo package
    - uses: actions/upload-artifact@4
      with:
        name: hw-rs
        path: target/release/hw-rs
